### ISSUE TITLE
The name of this application

### ISSUE THREAD

**Issue by fython** [fython/LuSpeed#1]
We need a name which sounds amazing and funny. If you have any idea, plz write down the opinions from your brain's hole.

我们需要一个挺起非常震精、有趣的名字。如果你有什么好的想法，请务必把它从你的脑洞里拉出来贴在这ww。

**Comment by 1a57danc3** [comment]
擼速

**Comment by LBfY** [comment]
后羿射日

**Comment by MichelleMa** [comment]
撸至深

**Comment by fython** [comment]
已改名“撸大湿” (Fixed via 17cff46)
